WITH RECURSIVE generation_cte AS (
    SELECT 
        ID,
        1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    SELECT 
        e.ID,
        g.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA e
    INNER JOIN generation_cte g ON e.PARENT_ID = g.ID
),
childless AS (
    SELECT g.ID, g.GENERATION
    FROM generation_cte g
    LEFT JOIN ECOLI_DATA e ON g.ID = e.PARENT_ID
    WHERE e.ID IS NULL
)

SELECT 
    COUNT(*) AS COUNT,
    GENERATION
FROM childless
GROUP BY GENERATION
ORDER BY GENERATION;
