WITH A AS (
    SELECT 
        YEAR(DIFFERENTIATION_DATE) AS YEAR_DIFF, 
        MAX(SIZE_OF_COLONY) AS max_value
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT 
    YEAR(a.DIFFERENTIATION_DATE) AS YEAR,
    (b.max_value - a.SIZE_OF_COLONY) AS YEAR_DEV,
    a.ID
FROM ECOLI_DATA a
INNER JOIN A b ON YEAR(a.DIFFERENTIATION_DATE) = b.YEAR_DIFF
order by YEAR(a.DIFFERENTIATION_DATE) asc , YEAR_DEV asc