WITH A AS (
    SELECT 
        ID,
        FISH_TYPE,
        CASE
            WHEN LENGTH < 10 or length is null THEN 10
            ELSE LENGTH
        END AS LENGTH
    FROM FISH_INFO
)
SELECT 
    COUNT(ID) AS FISH_COUNT,
    MAX(LENGTH) AS MAX_LENGTH,
    FISH_TYPE
FROM A
GROUP BY FISH_TYPE
HAVING AVG(LENGTH) >= 33
ORDER BY FISH_TYPE;